language: cpp
compiler:
  - gcc
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libpng12-dev
      - libgtk2.0-dev
      - zlib1g-dev
before_script:
  - mkdir build
  - cd build
  - git clone https://github.com/ladislav-zezula/StormLib.git
  - cd StormLib
  - if [ $TRAVIS_OS_NAME == linux ]; then make -f Makefile.linux; export STORMLIB="$PWD/libStorm.a"; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install libtomcrypt; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then make -f Makefile.mac; export STORMLIB="$PWD/StormLib.a"; fi
  - find . -name "*.o" | xargs ar rcs "$PWD/StormLib.a"
  - cd ..
  - curl -L https://github.com/Wargus/stratagus/archive/master.zip -O master.zip || true
  - unzip master.zip
  - cmake -DSTORMLIB_INCLUDE_DIR="$PWD/StormLib/src" -DSTORMLIB_LIBRARY="$STORMLIB" -DSTRATAGUS=stratagus -DSTRATAGUS_INCLUDE_DIR="$PWD/stratagus-master/gameheaders" ..
script: make
