configuration:
  - Release
before_build:
  - mkdir build
  - cd build
  - appveyor DownloadFile https://github.com/Wargus/win32-stratagus-dependencies/releases/download/master-builds/dependencies.zip
  - 7z x dependencies.zip
  - appveyor DownloadFile https://github.com/Wargus/stratagus/archive/master.zip
  - 7z x master.zip
  - appveyor DownloadFile https://github.com/jimpark/unsis/releases/download/2.50.0/nsis-2.50.0-Unicode-setup.exe
  - nsis-2.50.0-Unicode-setup.exe /S /D=C:\Program Files (x86)\NSIS
  - cmake -G "Visual Studio 14 2015" -T v120_xp -DCMAKE_PREFIX_PATH="%cd%\\dependencies" -DSTRATAGUS=stratagus -DSTRATAGUS_INCLUDE_DIR="%cd%\\stratagus-master\\gameheaders" -DENABLE_NSIS=ON ..
  - cd ..
artifacts:
  - path: build\Wargus-*.exe
deploy:
  release: master-builds
  description: 'Automatic builds from the master branch'
  provider: GitHub
  auth_token:
    secure: NMy2KE3EpZTjverxNzEAoBnlV+7VLGvwy3e1WEIrliFy3R1oxuT+AgGUDcRwv9y/
  artifact: /.*exe/
  draft: false
  prerelease: true
  on:
    branch: master
